service:
  name: cognito-authorizer-example
plugins:
  - serverless-webpack

provider:
  name: aws
  region: ap-southeast-1 # Default region to be used
  runtime: nodejs14.x
  environment:
    TOKEN_ISSUER: ${file(./config.json):TOKEN_ISSUER}
    JWKS_URI: ${file(./config.json):JWKS_URI}
custom:
  webpack:
     keepOutputDirectory: true
functions:
  authorizer:
    handler: handler.authorize
